server:
  url: https://wiediversistmeingarten.org/api/
station: 
  boxId: 4a936912-65db-475d-bcd6-9ee292079830
  environmentTimeDeltaInMinutes: 2 
  weightThreshold: 5 
  calibration_weight: 0
  terminal_weight: 0
misc:
  #loglevel can be either 0-NOTSET, 10-DEBUG, 20-INFO, 30-WARNING, 40-ERROR, 50-CRITICAL
  loglevel: 20